//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProductsOrders = new HashSet<ProductsOrders>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public decimal Cost { get; set; }
        public int StatusOrderID { get; set; }
        public int PointsID { get; set; }
    
        public virtual Points Points { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsOrders> ProductsOrders { get; set; }
    }
}
