//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumeApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParfumEntities : DbContext
    {
        private static ParfumEntities _parfumEntities;

        public ParfumEntities()
            : base("name=ParfumEntities")
        {
        }

        /// <summary>
        /// Возвращает контекст данных.
        /// </summary>
        /// <returns>Контекст данных.</returns>
        public static ParfumEntities GetContext()
        {
            if (_parfumEntities is null)
                _parfumEntities = new ParfumEntities();
            return _parfumEntities;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryProducts> CategoryProducts { get; set; }
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Manufactures> Manufactures { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Points> Points { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsOrders> ProductsOrders { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<UnitMetric> UnitMetric { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
